// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public interface DownloadDelegate
{
		
	void downloadDidFinishLoading(Download download);
	void downloadDidFail(Download download);
	void downloadDidFailConnectivity(Download download);
	void downloadDidFailNoAvailableSpace(Download download);
	void downloadDidReceiveData(Download download);	
	void downloadDidStart(Download download);
	void downloadDidPause(Download download);
	
}


