// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public interface DownloadManagerDelegate
{
	void DownloadDidFinishLoading(DownloadManager downloadManager,Download download);
	void DownloadDidFail(DownloadManager downloadManager,Download download);
	void DownloadDidReceiveData(DownloadManager downloadManager,Download download);
	void DownloadDidStart(DownloadManager downloadManager,Download download);

	void DownloadDidFinishLoadingAll(DownloadManager downloadManager);
	void DownloadDidStartLoadingAllForManager(DownloadManager downloadManager);


}


